-- Baseline for the 2025 and earlier schema.
-- Resolve this migration as applied for existing databases.

CREATE TABLE public.blacklist (
    user_id bigint NOT NULL,
    date_added timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT blacklist_pkey PRIMARY KEY (user_id)
);

CREATE TABLE public.canvas (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    locked boolean DEFAULT true NOT NULL,
    event_id integer,
    width integer NOT NULL,
    height integer NOT NULL,
    cooldown_length integer,
    start_coordinates integer[] DEFAULT '{1,1}'::integer[] NOT NULL,
    CONSTRAINT canvas_pkey PRIMARY KEY (id)
);

  CREATE TABLE public.cooldown (
    user_id bigint NOT NULL,
    canvas_id integer NOT NULL,
    cooldown_time timestamp with time zone,
    CONSTRAINT cooldown_pkey PRIMARY KEY (user_id, canvas_id)
  );

CREATE TABLE public.color (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    emoji_name text NOT NULL,
    emoji_id bigint NOT NULL,
    global boolean DEFAULT true NOT NULL,
    name text NOT NULL,
    rgba integer[] NOT NULL,
    CONSTRAINT color_pkey PRIMARY KEY (id)
);

CREATE TABLE public.discord_guild_record (
    guild_id bigint NOT NULL,
    name text NOT NULL,
    CONSTRAINT discord_guild_record_pkey PRIMARY KEY (guild_id)
);

CREATE TABLE public.discord_user_profile (
    user_id bigint NOT NULL,
    username text NOT NULL,
    profile_picture_url text,
    CONSTRAINT discord_user_profile_pkey PRIMARY KEY (user_id)
);

CREATE TABLE public.event (
    id integer NOT NULL,
    name text NOT NULL,
    CONSTRAINT event_pkey PRIMARY KEY (id)
);

CREATE TABLE public.frame (
    id text NOT NULL,
    canvas_id integer NOT NULL,
    owner_id bigint NOT NULL,
    is_guild_owned boolean DEFAULT false NOT NULL,
    name text NOT NULL,
    x_0 integer NOT NULL,
    x_1 integer NOT NULL,
    y_0 integer NOT NULL,
    y_1 integer NOT NULL,
    style_id integer,
    CONSTRAINT frame_pkey PRIMARY KEY (id)
);

CREATE TABLE public.guild (
    id bigint NOT NULL,
    manager_role bigint,
    invite text,
    CONSTRAINT guild_pkey PRIMARY KEY (id)
);

CREATE TABLE public.history (
    canvas_id integer NOT NULL,
    user_id bigint NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    color_id integer NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    guild_id bigint,
    CONSTRAINT history_pkey PRIMARY KEY (id)
);

CREATE TABLE public.info (
    title text NOT NULL,
    canvas_admin bigint[] NOT NULL,
    current_event_id integer NOT NULL,
    cached_canvas_ids integer[],
    highlight_color integer,
    admin_server_id bigint NOT NULL,
    current_emoji_server_id bigint NOT NULL,
    host_server_id bigint NOT NULL,
    event_role_id bigint,
    default_canvas_id integer,
    all_colors_global boolean DEFAULT false NOT NULL,
    CONSTRAINT info_pkey PRIMARY KEY (title)
);

CREATE TABLE public.participation (
    guild_id bigint NOT NULL,
    event_id bigint NOT NULL,
    color_id integer,
    CONSTRAINT participation_pkey PRIMARY KEY (guild_id, event_id)
);

CREATE TABLE public.pixel (
    canvas_id integer NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    color_id integer NOT NULL,
    CONSTRAINT pixel_pkey PRIMARY KEY (canvas_id, x, y)
);

CREATE TABLE public.session (
    id text NOT NULL,
    sid text NOT NULL,
    data text NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (id),
    CONSTRAINT session_sid_key UNIQUE (sid)
);

CREATE TABLE public."user" (
    id bigint NOT NULL,
    current_canvas_id integer,
    skip_confirm boolean DEFAULT false NOT NULL,
    cooldown_remind boolean DEFAULT false NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

ALTER TABLE public.blacklist
    ADD CONSTRAINT blacklist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);

ALTER TABLE public.canvas
    ADD CONSTRAINT canvas_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.event(id);

ALTER TABLE public.cooldown
    ADD CONSTRAINT cooldown_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id),
    ADD CONSTRAINT cooldown_canvas_id_fkey FOREIGN KEY (canvas_id) REFERENCES public.canvas(id);

ALTER TABLE public.discord_user_profile
    ADD CONSTRAINT discord_user_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);

ALTER TABLE public.frame
    ADD CONSTRAINT frame_canvas_id_fkey FOREIGN KEY (canvas_id) REFERENCES public.canvas(id);

ALTER TABLE public.guild
    ADD CONSTRAINT guild_id_fkey FOREIGN KEY (id) REFERENCES public.discord_guild_record(guild_id);

ALTER TABLE public.history
    ADD CONSTRAINT history_canvas_id_fkey FOREIGN KEY (canvas_id) REFERENCES public.canvas(id),
    ADD CONSTRAINT history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id),
    ADD CONSTRAINT history_color_id_fkey FOREIGN KEY (color_id) REFERENCES public.color(id),
    ADD CONSTRAINT history_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES public.guild(id);

ALTER TABLE public.info
    ADD CONSTRAINT info_current_event_id_fkey FOREIGN KEY (current_event_id) REFERENCES public.event(id);

ALTER TABLE public.participation
    ADD CONSTRAINT participation_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES public.guild(id),
    ADD CONSTRAINT participation_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.event(id),
    ADD CONSTRAINT participation_color_id_fkey FOREIGN KEY (color_id) REFERENCES public.color(id);

ALTER TABLE public.pixel
    ADD CONSTRAINT pixel_canvas_id_fkey FOREIGN KEY (canvas_id) REFERENCES public.canvas(id),
    ADD CONSTRAINT pixel_color_id_fkey FOREIGN KEY (color_id) REFERENCES public.color(id);

ALTER TABLE public."user"
    ADD CONSTRAINT user_current_canvas_id_fkey FOREIGN KEY (current_canvas_id) REFERENCES public.canvas(id);

CREATE UNIQUE INDEX pixel_canvas_id_x_y_key ON public.pixel (canvas_id, x, y);

CREATE VIEW public.most_frequent_color AS
SELECT
  DISTINCT ON (history.user_id, history.canvas_id) history.user_id,
  history.canvas_id,
  history.color_id,
  count(*) AS count
FROM
  history
GROUP BY
  history.user_id,
  history.color_id,
  history.canvas_id
ORDER BY
  history.user_id,
  history.canvas_id,
  (count(*)) DESC;

CREATE VIEW public.color_place_frequency AS
WITH time_diffs AS (
  SELECT
    history.user_id,
    history.canvas_id,
    (
      history."timestamp" - lag(history."timestamp") OVER (
        PARTITION BY history.user_id,
        history.canvas_id
        ORDER BY
          history."timestamp"
      )
    ) AS time_diff
  FROM
    history
  ORDER BY
    history."timestamp"
)
SELECT
  t.user_id,
  t.canvas_id,
  percentile_cont((0.5) :: double precision) WITHIN GROUP (
    ORDER BY
      t.time_diff
  ) AS median_time_diff
FROM
  time_diffs t
WHERE
  (t.time_diff > '00:00:00.1' :: INTERVAL)
GROUP BY
  t.user_id,
  t.canvas_id
HAVING
  (count(*) > 1);

CREATE VIEW public.most_frequent_color_guild AS
SELECT
  DISTINCT ON (history.guild_id, history.canvas_id) history.guild_id,
  history.canvas_id,
  history.color_id,
  count(*) AS count
FROM
  history
GROUP BY
  history.guild_id,
  history.color_id,
  history.canvas_id
ORDER BY
  history.guild_id,
  history.canvas_id,
  (count(*)) DESC;

CREATE VIEW public.color_place_frequency_guild AS
WITH time_diffs AS (
  SELECT
    history.guild_id,
    history.canvas_id,
    (
      history."timestamp" - lag(history."timestamp") OVER (
        PARTITION BY history.guild_id,
        history.canvas_id
        ORDER BY
          history."timestamp"
      )
    ) AS time_diff
  FROM
    history
  ORDER BY
    history."timestamp"
)
SELECT
  t.guild_id,
  t.canvas_id,
  percentile_cont((0.5) :: double precision) WITHIN GROUP (
    ORDER BY
      t.time_diff
  ) AS median_time_diff
FROM
  time_diffs t
WHERE
  (t.time_diff > '00:00:00.05' :: INTERVAL)
GROUP BY
  t.guild_id,
  t.canvas_id
HAVING
  (count(*) > 1);

CREATE VIEW public.leaderboard_guild AS
SELECT
  history.user_id,
  history.canvas_id,
  history.guild_id,
  count(*) AS total_pixels,
  rank() OVER (
    PARTITION BY history.canvas_id,
    history.guild_id
    ORDER BY
      (count(*)) DESC
  ) AS rank
FROM
  history
WHERE
  history.user_id NOT IN (SELECT user_id FROM blacklist)
GROUP BY
  history.user_id,
  history.canvas_id,
  history.guild_id;

CREATE VIEW public.guild_stats AS
SELECT
  lb.guild_id,
  lb.canvas_id,
  lb.total_pixels,
  mfc.color_id AS most_frequent_color_id,
  mfc.count AS color_count,
  cpf.median_time_diff AS place_frequency,
  h.most_recent_timestamp
FROM
  (
    (
      (
        (
          SELECT
            leaderboard_guild.canvas_id,
            leaderboard_guild.guild_id,
            (sum(leaderboard_guild.total_pixels)) :: integer AS total_pixels
          FROM
            leaderboard_guild
          GROUP BY
            leaderboard_guild.canvas_id,
            leaderboard_guild.guild_id
        ) lb
        LEFT JOIN most_frequent_color_guild mfc ON (
          (
            (lb.canvas_id = mfc.canvas_id)
            AND (lb.guild_id = mfc.guild_id)
          )
        )
      )
      LEFT JOIN color_place_frequency_guild cpf ON (
        (
          (lb.canvas_id = cpf.canvas_id)
          AND (lb.guild_id = cpf.guild_id)
        )
      )
    )
    LEFT JOIN (
      SELECT
        history.guild_id,
        history.canvas_id,
        max(history."timestamp") AS most_recent_timestamp
      FROM
        history
      GROUP BY
        history.guild_id,
        history.canvas_id
    ) h ON (
      (
        (lb.canvas_id = h.canvas_id)
        AND (lb.guild_id = h.guild_id)
      )
    )
  );

CREATE VIEW public.leaderboard AS
SELECT
  leaderboard_guild.user_id,
  leaderboard_guild.canvas_id,
  (sum(leaderboard_guild.total_pixels)) :: integer AS total_pixels,
  rank() OVER (
    PARTITION BY leaderboard_guild.canvas_id
    ORDER BY
      (sum(leaderboard_guild.total_pixels)) DESC
  ) AS rank
FROM
  leaderboard_guild
GROUP BY
  leaderboard_guild.user_id,
  leaderboard_guild.canvas_id;

CREATE VIEW public.user_stats AS
SELECT
  lb.user_id,
  lb.canvas_id,
  lb.total_pixels,
  lb.rank,
  mfc.color_id AS most_frequent_color_id,
  mfc.count AS color_count,
  cpf.median_time_diff AS place_frequency,
  h.most_recent_timestamp
FROM
  (
    (
      (
        leaderboard lb
        LEFT JOIN most_frequent_color mfc ON (
          (
            (lb.canvas_id = mfc.canvas_id)
            AND (lb.user_id = mfc.user_id)
          )
        )
      )
      LEFT JOIN color_place_frequency cpf ON (
        (
          (lb.canvas_id = cpf.canvas_id)
          AND (lb.user_id = cpf.user_id)
        )
      )
    )
    LEFT JOIN (
      SELECT
        history.user_id,
        history.canvas_id,
        max(history."timestamp") AS most_recent_timestamp
      FROM
        history
      GROUP BY
        history.user_id,
        history.canvas_id
    ) h ON (
      (
        (lb.canvas_id = h.canvas_id)
        AND (lb.user_id = h.user_id)
      )
    )
  );
